Lab#1
Andrikck/Svyryduk_Andrii_IPZ_31 pull request #1
Opened 2024-09-10 11:23 UTC by Andrikck

2024-09-11 07:24 UTC, vozniuk-lntu commented
hello

2024-09-11 07:37 UTC, vozniuk-lntu requested changes

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +<html lang="en">
en?

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +        <table>
table ми удаляєм

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +    <li>WebStudio</li>
логотип - це посиланя на гоовну сторінкку

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +                    <li><a href="">38 096 111 11 11</a></li>
вийми телефон з навігації і розмісти перед емейлом

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +
там де телофон tel:

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +    <p> <a href="/">WebStudio</a></p>
можеш P забрати

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +            <p><a href="">38-096-111-11-11</a></p>
задереш P
і додай tel: (загугли)
<a href="tel:+4733378901">+47 333 78 901</a>

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +                        <strong>Ольга Репіна</strong><br>
імʼя це H3
посада це просто абзац

2024-09-11 07:37 UTC, vozniuk-lntu commented on index.html
> +                <li><p><a href="mailto:info@devstudio.com">info@devstudio.com</a></p></li>
Р тут прибери

2024-09-11 07:37 UTC, vozniuk-lntu commented
1. Прибрати всі таблиці (хай все в стовпяик буде)
2. в тезі мейн має бути чотири секції (герой сайту, переваги, чим займаємся, команда)
3. додай ALT до всіх картинок (це короткий опис)

2024-09-11 09:43 UTC, Andrikck commented
На мою думку я завершив лаб 1

2024-09-17 10:53 UTC, vozniuk-lntu commented
описи картинок у другій секції

2024-09-17 10:54 UTC, vozniuk-lntu approved these changes

2024-09-17 10:55 UTC, merged